### ISSUE TITLE
Is it possible to add p99 to the request duration?

### ISSUE THREAD

**Issue by craigpastro** [szkiba/xk6-dashboard#16]
👋 First of all, xk6-dashboard is awesome. Thank you!

I was just wondering if it is possible to get p99 added to the request duration? I guess it is not there because p99 is not in the default http metrics of k6? And it won't be possible unless p99 is added to the default http metrics of k6? In any case, just wanted to confirm this.

Thank you!

**Comment by szkiba** [comment]
It is technologically possible to add p99. Although this would affect the core of the extension in addition to the ui.
How important is display p99 ?

**Comment by craigpastro** [comment]
I am load testing a high-request application and the p99 is important to me in that respect. That said, I can always see it in the summary at the end of the k6 run. Having it in xk6-dashboard would be a "nice to have" for me. It would be awesome if there was an option like `summaryTrendStats` to display the metrics that we are most interested in, but if it is not easy then I wouldn't give it much thought.

Thank you!

**Comment by szkiba** [comment]
Thank you for suggestion, customization is already in my mind. I'll add it when I find a right way of customization....

**Comment by szkiba** [comment]
Hi @craigpastro ,
It is done :) check v0.4.0 release.
In short: create `.dashboard.js` configuration file in current directory (or specify location in `config` parameter) with the following content:
```js
function addP99 (chart) {
  chart.series['http_req_duration_trend_p(99)'] = { label: 'p(99)' }
}

addP99(defaultConfig.tab('overview_snapshot').chart('http_req_duration'))
addP99(defaultConfig.tab('overview_cumulative').chart('http_req_duration'))

export default defaultConfig
```
That's it :)

**Comment by szkiba** [comment]
> Please let me know if I can be of any help.
@craigpastro  as you probably see, the most difficult part of sottware development for me is to write documentation in English :)
I'd welcome any contribution on documentation....

**Comment by craigpastro** [comment]
Oh wow! That was super fast. Thank you! I'll give it a try soon. And, for sure, I'll look for some opportunities to contribute to the documentation 👍 

Thanks again!
