### ISSUE TITLE
Does this extension supports output to a single html, like JMeter?

### ISSUE THREAD

**Issue by ukewea** [szkiba/xk6-dashboard#27]
Hi, I am currently using the k6 extension and find the live dashboard very helpful. 

I wonder if this extension generate a single HTML report of the test results, similar to JMeter? or there is any workaround for this? 

If not, I believe adding this feature would greatly enhance its usability and convenience, especially for offline result analysis and sharing.

Thanks for your attention to this matter.

**Comment by szkiba** [comment]
Hi,
Currently the best you can do is printing "report" tab to PDF file.
Is it suitable? Or you need HTML for some reason?

**Comment by ukewea** [comment]
Hi @szkiba,

Thanks for your response. In our specific situation, the requirement stems from our current evaluation process where we are comparing JMeter and k6 as potential tools to build a load testing suite for our product. We noticed that JMeter has a built-in feature for outputting reports in HTML format, a functionality that seems to be missing in k6. My expectation was that the xk6-dashboard could bridge this gap.

While PDFs are great in personal environment, they may not be as effective when integrated into CI/CD pipelines.

With that said, I wonder if there's any possibility for me to contribute to the project by implementing changes that could enable output in a functional HTML format at the end of the test. If such a modification is feasible, I would be glad to work on it and subsequently submit a pull request for your review.

Looking forward to your feedback on this proposal. Thank you.

**Comment by szkiba** [comment]
Hi @ukewea ,

I'm afraid xk6-dashboard is not the best tool for this task. CI/CD pipeline typically requires automatic report generation, while the xk6-dashboard report is generated in a web browser. The extension itself only sends the data via SSE stream and reports and charts are created from it in the browser.
A better choice is to save the data in JSON or CSV and generate a report from it. I think there are tools for that. If the existing tools are not suitable, I think it is worth creating this in JavaScript (Node.js)...

**Comment by ukewea** [comment]
Hi @szkiba 

Thank you so much for your valuable insight and suggestions, your guidance is highly appreciated. I'll close the issue now. Please feel free to reach out if there's any other assistance you can provide in the future.

Best regards.

**Comment by szkiba** [comment]
Hi @ukewea , I hope you will choose k6 :)
