### ISSUE TITLE
Feature request: save/export to HTML

### ISSUE THREAD

**Issue by Relex28** [szkiba/xk6-dashboard#36]
Love the dashboard especially the new replay function. it would be nice though to have the option to save/export to HTML. This so that it is easily integratable into pipeline testing/reporting.

love your work, Cheers

**Comment by szkiba** [comment]
Thank you for feedback. Single file HTML output is already on the roadmap, please be patient... (Might be a separated extension or part of xk6-dashboard)

**Comment by Relex28** [comment]
That’s awesome! I’ll be patient, anywhere I can follow what’s on the roadmap?

cheers

**Comment by szkiba** [comment]
@Relex28 the xk6-dashboard extension will be moved soon into grafana GH project. I'm not sure yet how roadmap will be handled. I'll join to Grafana Labs at the end of July and continue working on dashboard. Probably the k6 slack is the best place to keep your eyes on.
