### ISSUE TITLE
Example dashboard

### ISSUE THREAD

**Issue by afonsojramos** [szkiba/xk6-dashboard#4]
I've ran everything with the default configuration, however, the dashboard is completely empty when I open it.

Ideally we would get this:

![image](https://user-images.githubusercontent.com/19473034/172806154-f6c0255b-7459-44e3-bdca-e941b7a9ac8b.png)

But I was only getting a blank dashboard:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/19473034/172806609-d148b3ae-fada-41a5-b6e8-6bb51def7958.png">

Is there some step missing?

**Comment by showtimezz** [comment]
I had a similar issue, it turns out brave was blocking the requests to get the actual data. Check if you have a firewall or AdBlock running, that might help clear up the issue.

**Comment by jekakos** [comment]
Is it normal that I can not get access to http://127.0.0.1:5665/  after k6 work was finished?
What to do to get one?

**Comment by afonsojramos** [comment]
I've tried this again and now it appears to be working so I'll close the issue. If anyone encounters this in the future, I do recommend checking blocked requests.

@jekakos you have to open it while it is running I believe.

**Comment by jekakos** [comment]
> I've tried this again and now it appears to be working so I'll close the issue. If anyone encounters this in the future, I do recommend checking blocked requests.
> 
> @jekakos you have to open it while it is running I believe.

What was the problem? 
I checked 5665 port, but no process on it. I try to open dashboard after test finished

**Comment by Nijinsha** [comment]
@jekakos the Same issue here. It says refused to connect.
