### ISSUE TITLE
Example Dashboard is not Working

### ISSUE THREAD

**Issue by BaluM17** [szkiba/xk6-dashboard#5]
When I am running the performance script which you gave, I followed all the steps. But I am getting the error. that is dashboard output type is not available. Can you please help me in fixing this......
![image](https://user-images.githubusercontent.com/109271482/178922679-eaacca25-8a3b-4b73-b5f2-b7aa2b1f08d1.png)

**Comment by sswales** [comment]
I am also getting this same issue 😢

**Comment by feelgood-interface** [comment]
The k6 binary builds to the current directory. So make sure you are executing the current k6 binary, in case you already have another k6 in another environment path.

**Comment by louiske0911** [comment]
not work too...

**Comment by mkadirtan** [comment]
Same here

**Comment by szkiba** [comment]
@mkadirtan , @louiske0911  @baralraj, @BaluM17 did you try to build custom k6 or just clone the repo?
https://github.com/szkiba/xk6-dashboard#build
