### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by MyungChi** [szkiba/xk6-dashboard#8]
Hi. 

I am trying to build xk6 dashboard in my local env.
I am not familier with Go Lang.
I got the error as below. Can someone help to solve below issues ?

[myhost go]# which xk6
/usr/local/go/bin/xk6

[myhost go]# xk6 build --with github.com/szkiba/xk6-dashboard@latest
2023/02/07 11:07:16 [INFO] Temporary folder: /tmp/buildenv_2023-02-07-1107.893287387
2023/02/07 11:07:16 [INFO] Initializing Go module
2023/02/07 11:07:16 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init k6
go: creating new go.mod: module k6
2023/02/07 11:07:16 [INFO] Pinning versions
2023/02/07 11:07:16 [INFO] exec (timeout=0s): /usr/local/go/bin/go mod edit -require github.com/szkiba/xk6-dashboard@latest
**2023/02/07 11:07:16 [INFO] exec (timeout=0s): /usr/local/go/bin/go mod tidy -compat=1.17
flag provided but not defined: -compat
usage: go mod tidy [-e] [-v]
Run 'go help mod tidy' for details.
2023/02/07 11:07:16 [INFO] Cleaning up temporary folder: /tmp/buildenv_2023-02-07-1107.893287387
2023/02/07 11:07:16 [FATAL] exit status 2**

[myhost go]# go version
go version go1.16.5 linux/amd64

[myhost go]# go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2764039167=/tmp/go-build -gno-record-gcc-switches"

BRs.

**Comment by szkiba** [comment]
I guess your go compiler is too old (1.16.5), I recommend upgrade golang.
